# Generated by Django 4.2.5 on 2023-09-16 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import goldenstart.models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.BigIntegerField(default=0)),
                ('download_count', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='mail_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PDF', 'pdf'), ('EXCEL', 'excel')], max_length=100)),
                ('document', models.FileField(upload_to=goldenstart.models.document_upload_file)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
